-- ============================================================
-- Design Tasks App — Supabase schema
-- Выполните этот файл целиком в Supabase Dashboard → SQL Editor
-- ============================================================

-- 1) Профили пользователей (роль: baer/designer)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  role text not null check (role in ('buyer', 'designer')),
  created_at timestamptz default now()
);

alter table public.profiles enable row level security;

create policy "profiles are viewable by any authenticated user"
  on public.profiles for select
  to authenticated
  using (true);

create policy "users can insert their own profile"
  on public.profiles for insert
  to authenticated
  with check (auth.uid() = id);

create policy "users can update their own profile"
  on public.profiles for update
  to authenticated
  using (auth.uid() = id);

-- 2) Задачи
create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  type text,
  priority text,
  status text not null default 'Ожидание',
  format jsonb default '[]'::jsonb,
  geo text,
  language text,
  celebs jsonb default '[]'::jsonb,
  description text,
  task_link text,
  creative_link text,
  posted_by text,
  created_at timestamptz default now(),
  status_updated_at timestamptz
);

alter table public.tasks enable row level security;

create policy "authenticated users can read all tasks"
  on public.tasks for select
  to authenticated
  using (true);

create policy "authenticated users can insert tasks"
  on public.tasks for insert
  to authenticated
  with check (true);

create policy "authenticated users can update tasks"
  on public.tasks for update
  to authenticated
  using (true);

create policy "authenticated users can delete tasks"
  on public.tasks for delete
  to authenticated
  using (true);

-- 3) Память по селебам на гео
create table if not exists public.celebs_by_geo (
  geo text primary key,
  names jsonb default '[]'::jsonb
);

alter table public.celebs_by_geo enable row level security;

create policy "authenticated users can read celebs"
  on public.celebs_by_geo for select
  to authenticated
  using (true);

create policy "authenticated users can upsert celebs"
  on public.celebs_by_geo for insert
  to authenticated
  with check (true);

create policy "authenticated users can update celebs"
  on public.celebs_by_geo for update
  to authenticated
  using (true);

-- 4) Realtime (чтобы задачи обновлялись у всех участников live)
alter publication supabase_realtime add table public.tasks;

-- 5) Хранилище для креативов
insert into storage.buckets (id, name, public)
values ('creatives', 'creatives', true)
on conflict (id) do nothing;

create policy "anyone authenticated can upload creatives"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'creatives');

create policy "anyone can view creatives"
  on storage.objects for select
  to public
  using (bucket_id = 'creatives');

-- ============================================================
-- ГОТОВО. Дальше:
-- 1. Authentication → Providers → Email → выключите "Confirm email"
--    (для прототипа, чтобы не настраивать почтовый SMTP).
-- 2. Project Settings → API → скопируйте Project URL и anon public key
--    в .env (см. .env.example в корне проекта).
-- ============================================================
